// Tablero administrativo. Cada concepto usa una sola fuente:
// ventas -> ventas; cobros -> pagos; flujo/gastos -> movimientosFinancieros;
// conciliacion -> cajas. Las monedas nunca se convierten con una cotizacion actual.
var ADM_PERIODO='mes',ADM_DESDE='',ADM_HASTA='',ADM_RANK='unidades';

function admFecha(v){if(!v)return null;if(v instanceof Date)return v;var s=String(v),p=s.split('/');if(p.length===3)return new Date(+p[2],+p[1]-1,+p[0]);var d=new Date(s);return isNaN(d)?null:d;}
function admIso(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function admLimites(tipo,base){var h=new Date(base||new Date());h.setHours(23,59,59,999);var d=new Date(h);d.setHours(0,0,0,0);if(tipo==='semana'){var n=(d.getDay()+6)%7;d.setDate(d.getDate()-n);}else if(tipo==='mes')d=new Date(h.getFullYear(),h.getMonth(),1);else if(tipo==='anio')d=new Date(h.getFullYear(),0,1);else if(tipo==='rango'){d=admFecha(ADM_DESDE)||d;h=admFecha(ADM_HASTA)||h;h.setHours(23,59,59,999);}return {desde:d,hasta:h};}
function admAnterior(l){var ms=l.hasta-l.desde+1,d=new Date(l.desde.getTime()-ms),h=new Date(l.desde.getTime()-1);return {desde:d,hasta:h};}
function admDentro(v,l){var d=admFecha(v);return !!d&&d>=l.desde&&d<=l.hasta;}
function admFechaEntidad(x){return x.fechaHora||x.fecha||x.aperturaFechaHora||'';}
function admMoneda(x){return x.moneda==='USD'?'USD':'ARS';}
function admSumaMoneda(xs,valor){var r={ARS:0,USD:0};xs.forEach(function(x){r[admMoneda(x)]+=Number(valor(x)||0);});return r;}
function admFmt(r){var a=[];if(Math.abs(r.ARS)>.009||!r.USD)a.push(posDinero(r.ARS,'ARS'));if(Math.abs(r.USD)>.009)a.push(posDinero(r.USD,'USD'));return a.join(' · ');}
function admResta(a,b){return {ARS:a.ARS-b.ARS,USD:a.USD-b.USD};}
function admDiv(a,n){return {ARS:n?a.ARS/n:0,USD:n?a.USD/n:0};}
function admPct(a,b){return b?((a-b)/Math.abs(b))*100:null;}
function admComparacion(actual,anterior){var partes=[];['ARS','USD'].forEach(function(m){if(Math.abs(actual[m])>.009||Math.abs(anterior[m])>.009){var p=admPct(actual[m],anterior[m]);partes.push(m+' '+(p===null?'sin base':((p>=0?'+':'')+p.toLocaleString('es-AR',{maximumFractionDigits:1})+'%')));}});return partes.join(' · ');}
function admVentaActiva(v){return v.tipoRegistro==='pos'?v.estado!=='anulada':(typeof ventaValidaParaMetricas==='function'?ventaValidaParaMetricas(v):v.estadoVenta!=='Anulada'&&v.estadoVenta!=='Devuelta');}
function admVentaMonto(v){return Number(v.tipoRegistro==='pos'?v.total:v.precio)||0;}
function admVentaCosto(v){return Number(v.tipoRegistro==='pos'?v.costoTotal:v.costo)||0;}
function admLinea(v){return v.tipoRegistro==='pos'?'Accesorios / POS':'Equipos';}
function admPagoActivo(p){return p.estado!=='revertido'&&p.estado!=='anulado';}
function admEsCompensatorio(m){return m.tipo==='reversion_venta'||m.tipo==='reversion_venta_equipo'||m.tipo==='movimiento_compensatorio'||m.tipoEgreso==='compensatorio';}
function admEsGasto(m){return Number(m.monto)<0&&m.tipo==='egreso_manual'&&m.tipoEgreso==='gasto_operativo'&&!admEsCompensatorio(m);}
function admDatos(l){
  var ventas=(window.VENTAS||[]).filter(function(v){return admVentaActiva(v)&&admDentro(admFechaEntidad(v),l);});
  var pagos=(window.PAGOS_ADMIN||[]).filter(function(p){return admPagoActivo(p)&&admDentro(admFechaEntidad(p),l);});
  var movs=(window.MOVIMIENTOS_FINANCIEROS_ADMIN||[]).filter(function(m){return admDentro(admFechaEntidad(m),l);});
  var gastos=movs.filter(admEsGasto),cierres=(window.CIERRES_CAJA||[]).filter(function(c){return c.estado==='cerrada'&&admDentro(c.fechaNegocio||c.cierreFechaHora,l);});
  var venta=admSumaMoneda(ventas,admVentaMonto),costo=admSumaMoneda(ventas,admVentaCosto),margen=admResta(venta,costo),cobrado=admSumaMoneda(pagos,function(p){return p.monto;}),gasto=admSumaMoneda(gastos,function(m){return Math.abs(Number(m.monto));}),resultado=admResta(margen,gasto);
  var unidades=ventas.reduce(function(s,v){return s+(v.tipoRegistro==='pos'?(v.items||[]).reduce(function(a,i){return a+Number(i.cantidad||0);},0):1);},0);
  return {ventas:ventas,pagos:pagos,movs:movs,gastos:gastos,cierres:cierres,venta:venta,costo:costo,margen:margen,cobrado:cobrado,gasto:gasto,resultado:resultado,unidades:unidades};
}
function admCard(t,v,d,cl){return '<div class="sc"><div class="scl">'+esc(t)+'</div><div class="scv '+(cl||'')+'">'+v+'</div><small>'+esc(d||'')+'</small></div>';}
function admSetPeriodo(p){ADM_PERIODO=p;renderAdminDashboard();}
function admRango(){ADM_DESDE=val('admDesde');ADM_HASTA=val('admHasta');ADM_PERIODO='rango';renderAdminDashboard();}
function admTabla(titulo,heads,rows){return '<section class="adm-sec"><div class="ct">'+esc(titulo)+'</div><div class="tw"><table><thead><tr>'+heads.map(function(h){return '<th>'+esc(h)+'</th>';}).join('')+'</tr></thead><tbody>'+((rows.length?rows:[['Sin datos para el período']]).map(function(r){return '<tr>'+r.map(function(c){return '<td>'+c+'</td>';}).join('')+'</tr>';}).join(''))+'</tbody></table></div></section>';}
function admAgrupar(xs,key,val){var r={};xs.forEach(function(x){var k=key(x)||'Sin especificar';if(!r[k])r[k]={nombre:k,ARS:0,USD:0,cantidad:0};r[k][admMoneda(x)]+=Number(val(x)||0);r[k].cantidad++;});return Object.keys(r).map(function(k){return r[k];});}
function admLineas(d){var nombres=['Accesorios / POS','Equipos','Reparaciones'];return nombres.map(function(n){var vs=d.ventas.filter(function(v){return admLinea(v)===n;}),ps=d.pagos.filter(function(p){if(n==='Reparaciones')return p.origenTipo==='reparacion';if(n==='Equipos')return p.origenTipo==='venta_equipo';return !p.origenTipo||p.origenTipo==='venta'||p.ventaId;});var venta=admSumaMoneda(vs,admVentaMonto),cobro=admSumaMoneda(ps,function(p){return p.monto;}),margen=admResta(venta,admSumaMoneda(vs,admVentaCosto)),ops=n==='Reparaciones'?Object.keys(ps.reduce(function(a,p){a[p.origenId||p.reparacionId||p.id]=1;return a;},{})).length:vs.length;return [esc(n),n==='Reparaciones'?'—':admFmt(venta),admFmt(cobro),String(ops),admFmt(admDiv(n==='Reparaciones'?cobro:venta,ops)),n==='Reparaciones'?'<span class="mu">No calculado: faltan costos vinculados</span>':admFmt(margen)];});}
function admProductos(d){var map={},catalogo={};(window.PRODUCTOS_POS||[]).forEach(function(p){catalogo[p.id]=p;});d.ventas.filter(function(v){return v.tipoRegistro==='pos';}).forEach(function(v){(v.items||[]).forEach(function(i){var k=i.productoId||i.nombre,p=catalogo[i.productoId]||{};if(!map[k])map[k]={nombre:i.nombre||'Producto',categoria:i.categoria||p.categoria||'Sin categoría',subcategoria:i.subcategoria||p.subcategoria||'',moneda:i.moneda||v.moneda||'ARS',unidades:0,venta:0,costo:0,categoriaActual:!i.categoria&&!!p.categoria};var x=map[k],q=Number(i.cantidad||0);x.unidades+=q;x.venta+=Number(i.precioFinal||0)*q;x.costo+=Number(i.costoTotal!=null?i.costoTotal:Number(i.costoUnitario||0)*q);});});var a=Object.keys(map).map(function(k){var x=map[k];x.margen=x.venta-x.costo;x.pct=x.venta?x.margen/x.venta*100:0;return x;});a.sort(function(a,b){return (b[ADM_RANK]||0)-(a[ADM_RANK]||0);});return a;}
function admRank(p){ADM_RANK=p;renderAdminDashboard();}
function admCategorias(productos){var m={},tot={ARS:0,USD:0};productos.forEach(function(p){var k=p.categoria+' · '+(p.subcategoria||'Sin subcategoría')+' · '+p.moneda;if(!m[k])m[k]={nombre:p.categoria+' · '+(p.subcategoria||'Sin subcategoría'),moneda:p.moneda,unidades:0,venta:0,margen:0};m[k].unidades+=p.unidades;m[k].venta+=p.venta;m[k].margen+=p.margen;tot[p.moneda]+=p.venta;});return Object.keys(m).map(function(k){m[k].part=tot[m[k].moneda]?m[k].venta/tot[m[k].moneda]*100:0;return m[k];}).sort(function(a,b){return b.venta-a.venta;});}
function admTemporales(d){var dias=['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'],m={};dias.forEach(function(x){m[x]={nombre:x,ARS:0,USD:0,ops:0,dias:{}};});d.ventas.forEach(function(v){var f=admFecha(admFechaEntidad(v)),x=m[dias[f.getDay()]];x[admMoneda(v)]+=admVentaMonto(v);x.ops++;x.dias[admIso(f)]=1;});return dias.map(function(k){var x=m[k],n=Object.keys(x.dias).length;return [k,admFmt(x),admFmt(admDiv(x,n)),String(x.ops),admFmt(admDiv(x,x.ops))];});}
function admPorDiaMes(d){var m={};d.ventas.forEach(function(v){var f=admFecha(admFechaEntidad(v)),k=f.getDate();if(!m[k])m[k]={dia:k,ARS:0,USD:0,ops:0};m[k][admMoneda(v)]+=admVentaMonto(v);m[k].ops++;});return Object.keys(m).map(function(k){return m[k];}).sort(function(a,b){return a.dia-b.dia;});}
function admMeses(d){var m={};function base(k){return m[k]||(m[k]={mes:k,ARS:0,USD:0,costoARS:0,costoUSD:0,gastoARS:0,gastoUSD:0,ops:0});}d.ventas.forEach(function(v){var k=admIso(admFecha(admFechaEntidad(v))).slice(0,7),x=base(k),mo=admMoneda(v);x[mo]+=admVentaMonto(v);x['costo'+mo]+=admVentaCosto(v);x.ops++;});d.gastos.forEach(function(g){var k=admIso(admFecha(admFechaEntidad(g))).slice(0,7);base(k)['gasto'+admMoneda(g)]+=Math.abs(Number(g.monto||0));});return Object.keys(m).sort().map(function(k){return m[k];});}
function admInventario(){var ps=(window.PRODUCTOS_POS||[]).filter(function(p){return p.activo!==false;}),u=0,c={ARS:0,USD:0},v={ARS:0,USD:0},b=0,s=0;ps.forEach(function(p){var q=Number(p.stockActual||0);u+=q;c[admMoneda(p)]+=q*Number(p.costo||0);v[admMoneda(p)]+=q*Number(p.precio||0);if(p.controlaStock&&q<=2)b++;if(p.controlaStock&&q<=0)s++;});return {productos:ps.length,unidades:u,costo:c,venta:v,bajo:b,sin:s};}
function renderAdminDashboard(){
  if(!puede('ver_balance')){showView('reps');return;}var cnt=el('cnt'),l=admLimites(ADM_PERIODO),d=admDatos(l),ant=admDatos(admAnterior(l)),ops=d.ventas.length,ticket=admDiv(d.venta,ops),productos=admProductos(d),cats=admCategorias(productos),inv=admInventario();
  var margenPct={ARS:d.venta.ARS?d.margen.ARS/d.venta.ARS*100:0,USD:d.venta.USD?d.margen.USD/d.venta.USD*100:0};
  cnt.innerHTML='<div class="adm-head"><div><div class="ct">Administración</div><div class="mu">Ventas, cobros, resultado y flujo separados por su fuente real.</div></div><div class="adm-filtros">'+['hoy','semana','mes','anio'].map(function(p){return '<button class="btn btn-sm '+(ADM_PERIODO===p?'btn-p':'btn-g')+'" onclick="admSetPeriodo(\''+p+'\')">'+({hoy:'Hoy',semana:'Semana',mes:'Mes',anio:'Año'})[p]+'</button>';}).join('')+'<input id="admDesde" type="date" value="'+esc(ADM_DESDE)+'"><input id="admHasta" type="date" value="'+esc(ADM_HASTA)+'"><button class="btn btn-g btn-sm" onclick="admRango()">Aplicar rango</button></div></div>'+
  '<div class="adm-note">Importes ARS y USD se muestran separados. No se convierten con cotizaciones actuales.'+((window.PAGOS_ADMIN_LIMITADO||window.MOVIMIENTOS_ADMIN_LIMITADO)?' ⚠ La ventana de 2.000 registros fue alcanzada: los períodos largos pueden estar incompletos.':'')+'</div><div class="sc-row">'+admCard('Ventas netas',admFmt(d.venta),admComparacion(d.venta,ant.venta)+' vs período anterior','cb')+admCard('Cobrado',admFmt(d.cobrado),admComparacion(d.cobrado,ant.cobrado)+' · fuente: pagos','cg')+admCard('Margen bruto',admFmt(d.margen),admComparacion(d.margen,ant.margen),'cg')+admCard('Margen %','ARS '+margenPct.ARS.toFixed(1)+'% · USD '+margenPct.USD.toFixed(1)+'%','Costo histórico vendido','')+admCard('Operaciones',ops,admComparacion({ARS:ops,USD:0},{ARS:ant.ventas.length,USD:0}),'')+admCard('Unidades vendidas',d.unidades,'Ventas activas','')+admCard('Ticket promedio',admFmt(ticket),'Venta / operación','')+admCard('Egresos operativos',admFmt(d.gasto),admComparacion(d.gasto,ant.gasto),'co')+admCard('Resultado operativo estimado',admFmt(d.resultado),'Margen bruto − gastos categorizados','cg')+'</div>';
  cnt.innerHTML+=admTabla('Líneas de negocio',['Línea','Ventas','Cobros','Operaciones','Ticket promedio','Margen bruto'],admLineas(d));
  cnt.innerHTML+='<section class="adm-sec"><div class="adm-title"><div class="ct">Productos POS</div><select onchange="admRank(this.value)"><option value="unidades"'+(ADM_RANK==='unidades'?' selected':'')+'>Unidades</option><option value="venta"'+(ADM_RANK==='venta'?' selected':'')+'>Facturación</option><option value="margen"'+(ADM_RANK==='margen'?' selected':'')+'>Margen bruto</option><option value="pct"'+(ADM_RANK==='pct'?' selected':'')+'>Margen %</option></select></div></section>'+admTabla('Ranking de productos',['Producto','Categoría','Subcategoría','Unidades','Ventas netas','Costo histórico','Margen','Margen %'],productos.slice(0,30).map(function(p){return [esc(p.nombre),esc(p.categoria)+(p.categoriaActual?' <span class="mu">(actual)</span>':''),esc(p.subcategoria||'—'),String(p.unidades),posDinero(p.venta,p.moneda),posDinero(p.costo,p.moneda),posDinero(p.margen,p.moneda),p.pct.toFixed(1)+'%'];}));
  cnt.innerHTML+=admTabla('Categorías y subcategorías',['Categoría','Unidades','Ventas','Margen','Participación'],cats.map(function(c){return [esc(c.nombre),String(c.unidades),posDinero(c.venta,c.moneda),posDinero(c.margen,c.moneda),c.part.toFixed(1)+'% de '+c.moneda];}));
  cnt.innerHTML+=admTabla('Actividad por día de semana',['Día','Ventas','Promedio por día activo','Operaciones','Ticket promedio'],admTemporales(d));
  cnt.innerHTML+=admTabla('Actividad por día del mes',['Día','Ventas','Operaciones','Ticket promedio'],admPorDiaMes(d).map(function(x){return [String(x.dia),admFmt(x),String(x.ops),admFmt(admDiv(x,x.ops))];}));
  cnt.innerHTML+=admTabla('Evolución mensual',['Mes','Ventas','Margen bruto','Operaciones','Ticket promedio','Gastos','Resultado operativo estimado'],admMeses(d).map(function(x){var v={ARS:x.ARS,USD:x.USD},m={ARS:x.ARS-x.costoARS,USD:x.USD-x.costoUSD},g={ARS:x.gastoARS,USD:x.gastoUSD};return [x.mes,admFmt(v),admFmt(m),String(x.ops),admFmt(admDiv(v,x.ops)),admFmt(g),admFmt(admResta(m,g))];}));
  var gastos=admAgrupar(d.gastos,function(m){return m.categoria;},function(m){return Math.abs(m.monto);}),gt=d.gasto;
  cnt.innerHTML+=admTabla('Gastos operativos por categoría',['Categoría','Importe','Participación','Movimientos'],gastos.sort(function(a,b){return b.ARS+b.USD-a.ARS-a.USD;}).map(function(g){var pa=gt.ARS?g.ARS/gt.ARS*100:0,pu=gt.USD?g.USD/gt.USD*100:0;return [esc(g.nombre),admFmt(g),'ARS '+pa.toFixed(1)+'% · USD '+pu.toFixed(1)+'%',String(g.cantidad)];}));
  cnt.innerHTML+=admTabla('Detalle de gastos categorizados',['Fecha','Categoría','Subcategoría','Cuenta','Descripción','Importe'],d.gastos.map(function(g){return [esc(posFecha(admFechaEntidad(g))),esc(g.categoria||'Sin categoría'),esc(g.subcategoria||'—'),esc(g.cuenta||'—'),esc(g.descripcion||'—'),posDinero(Math.abs(Number(g.monto||0)),admMoneda(g))];}));
  var medios=admAgrupar(d.pagos,function(p){return p.medio;},function(p){return p.monto;}),cuentas=admAgrupar(d.movs,function(m){return m.cuenta;},function(m){return m.monto;}),ing=admSumaMoneda(d.movs.filter(function(m){return Number(m.monto)>0;}),function(m){return m.monto;}),egr=admSumaMoneda(d.movs.filter(function(m){return Number(m.monto)<0;}),function(m){return Math.abs(m.monto);});
  cnt.innerHTML+=admTabla('Cobros por medio',['Medio','Monto','Operaciones'],medios.map(function(x){return [esc(x.nombre),admFmt(x),String(x.cantidad)];}))+admTabla('Flujo de dinero',['Concepto','Importe'],[['Ingresos financieros',admFmt(ing)],['Egresos financieros',admFmt(egr)],['Flujo neto',admFmt(admResta(ing,egr))]])+admTabla('Movimientos por cuenta',['Cuenta','Flujo neto','Movimientos'],cuentas.map(function(x){return [esc(x.nombre),admFmt(x),String(x.cantidad)];}));
  cnt.innerHTML+='<section class="adm-sec"><div class="ct">Inventario administrativo</div><div class="sc-row">'+admCard('Productos activos',inv.productos,'')+admCard('Unidades en stock',inv.unidades,'')+admCard('Stock a costo',admFmt(inv.costo),'Valor según costo actual del producto')+admCard('Venta potencial',admFmt(inv.venta),'No representa una venta realizada')+admCard('Stock bajo',inv.bajo,'Dos unidades o menos','co')+admCard('Sin stock',inv.sin,'Productos activos controlados','co')+'</div></section>';
  var dif=d.cierres.filter(function(c){return Math.abs(Number(c.diferencia||0))>.009;}),alertas=[];if(inv.sin)alertas.push(inv.sin+' producto(s) sin stock.');if(dif.length)alertas.push(dif.length+' cierre(s) con diferencia en el período.');if(productos[0])alertas.push('Producto destacado por '+ADM_RANK+': '+productos[0].nombre+'.');if(gastos[0])alertas.push('Mayor gasto operativo: '+gastos[0].nombre+' ('+admFmt(gastos[0])+').');var pv=admPct(d.venta.ARS,ant.venta.ARS);if(pv!==null&&Math.abs(pv)>=20)alertas.push('Ventas ARS '+(pv<0?'cayeron ':'subieron ')+Math.abs(pv).toFixed(1)+'% contra el período anterior.');cnt.innerHTML+='<section class="adm-sec"><div class="ct">Alertas administrativas</div>'+(alertas.map(function(a){return '<div class="adm-alert">⚠ '+esc(a)+'</div>';}).join('')||'<div class="empty">Sin alertas determinísticas para el período.</div>')+'</section><div class="adm-note"><b>Exactas:</b> ventas POS, cobros estructurados, movimientos, cierres, unidades y costos históricos POS/equipos. <b>Estimado:</b> resultado operativo, porque sólo descuenta gastos manuales correctamente categorizados. El margen de reparaciones no se calcula.</div>';
}
window.renderAdminDashboard=renderAdminDashboard;window.admSetPeriodo=admSetPeriodo;window.admRango=admRango;window.admRank=admRank;
