// Caja física: sesiones de apertura/cierre sobre movimientosFinancieros existentes.
function cajaActualAbierta(){return window.CAJA_ACTUAL&&CAJA_ACTUAL.estado==='abierta'?CAJA_ACTUAL:null;}
function cajaMovimientos(caja){var desde=String(caja&&caja.aperturaFechaHora||'');return (window.MOVIMIENTOS_FINANCIEROS_POS||[]).filter(function(m){return m.cajaId?m.cajaId===caja.id:String(m.fechaHora||'')>=desde;});}
function cajaResumen(caja){var movs=cajaMovimientos(caja),medio={},cuenta={},ing=0,egr=0,ingEf=0,egrEf=0,moneda=caja.moneda||'ARS';movs.forEach(function(m){var n=Number(m.monto||0),mo=m.moneda||'ARS',km=(m.medio||'Sin medio')+' · '+mo,kc=(m.cuenta||'Sin cuenta')+' · '+mo;medio[km]=(medio[km]||0)+n;cuenta[kc]=(cuenta[kc]||0)+n;if(mo===moneda){if(n>=0)ing+=n;else egr+=Math.abs(n);}if(m.medio==='Efectivo'&&mo===moneda){if(n>=0)ingEf+=n;else egrEf+=Math.abs(n);}});return {movimientos:movs,ingresosEfectivo:ingEf,egresosEfectivo:egrEf,efectivoEsperado:Number(caja.efectivoInicial||0)+ingEf-egrEf,totalesPorMedio:medio,totalesPorCuenta:cuenta,totalIngresos:ing,totalEgresos:egr};}
function cajaAbrirModal(){posModal('Abrir caja','<div class="pos-form"><label>Efectivo inicial<input id="caInicial" type="number" min="0" step="0.01" value="0"></label><label>Moneda<select id="caMoneda"><option>ARS</option><option>USD</option></select></label><label class="full">Observación<input id="caObs" placeholder="Opcional"></label></div>',function(){var b=el('posModalGuardar');b.disabled=true;FB.abrirCaja({efectivoInicial:Number(val('caInicial')||0),moneda:val('caMoneda'),observacion:val('caObs')},function(err){b.disabled=false;if(err){toast(err,'var(--rd)');return;}posCerrarModal();toast('Caja abierta');});},'Abrir caja');}
function cajaMovimientoModal(signo){if(!cajaActualAbierta()){toast('Primero abrí la caja','var(--rd)');return;}var ingreso=signo>0;posModal(ingreso?'Ingreso manual':'Egreso manual','<div class="pos-form"><label>Importe<input id="cmMonto" type="number" min="0" step="0.01"></label><label>Moneda<select id="cmMoneda"><option>ARS</option><option>USD</option></select></label><label>Medio<select id="cmMedio"><option>Efectivo</option><option>Transferencia</option><option>Débito</option><option>Crédito</option><option>Mercado Pago</option><option>Otro</option></select></label><label>Cuenta<input id="cmCuenta" value="Caja efectivo"></label><label>Categoría<input id="cmCategoria" placeholder="Caja chica, retiro..."></label><label class="full">Descripción / nota<input id="cmNota" placeholder="Motivo del movimiento"></label></div>',function(){var b=el('posModalGuardar');b.disabled=true;FB.movimientoManualCaja({monto:signo*Math.abs(Number(val('cmMonto')||0)),moneda:val('cmMoneda'),medio:val('cmMedio'),cuenta:val('cmCuenta'),categoria:val('cmCategoria'),descripcion:val('cmNota')},function(err){b.disabled=false;if(err){toast(err,'var(--rd)');return;}posCerrarModal();toast(ingreso?'Ingreso registrado':'Egreso registrado');});},'Registrar');}
function cajaCerrarModal(){var c=cajaActualAbierta();if(!c)return;var r=cajaResumen(c),mon=c.moneda||'ARS';posModal('Cerrar caja','<div class="pos-ticket-preview"><div><span>Efectivo inicial</span><b>'+posDinero(c.efectivoInicial,mon)+'</b></div><div><span>Ingresos en efectivo</span><b>'+posDinero(r.ingresosEfectivo,mon)+'</b></div><div><span>Egresos en efectivo</span><b>'+posDinero(r.egresosEfectivo,mon)+'</b></div><div class="total"><span>Efectivo esperado</span><b>'+posDinero(r.efectivoEsperado,mon)+'</b></div></div>'+cajaMapaHtml('Ventas/cobros por medio',r.totalesPorMedio)+cajaMapaHtml('Ventas/cobros por cuenta',r.totalesPorCuenta)+'<div class="pos-form" style="margin-top:12px"><label>Efectivo contado<input id="ccContado" type="number" min="0" step="0.01" oninput="cajaDiferenciaDom()"></label><label class="full">Observación / motivo diferencia<input id="ccObs"></label></div><div id="ccDif" class="pos-diferencia"></div>',function(){var contado=Number(val('ccContado')),dif=contado-r.efectivoEsperado;if(!Number.isFinite(contado)||contado<0){toast('Ingresá el efectivo contado','var(--rd)');return;}if(Math.abs(dif)>0.009&&!val('ccObs').trim()){toast('Indicá el motivo de la diferencia','var(--rd)');return;}var b=el('posModalGuardar');b.disabled=true;FB.cerrarCaja({resumen:r,efectivoContado:contado,observacion:val('ccObs')},function(err){b.disabled=false;if(err){toast(err,'var(--rd)');return;}posCerrarModal();toast('Caja cerrada');});},'Confirmar cierre');}
function cajaDiferenciaDom(){var c=cajaActualAbierta(),e=el('ccDif');if(!c||!e)return;var d=Number(val('ccContado')||0)-cajaResumen(c).efectivoEsperado;e.textContent='Diferencia: '+posDinero(d,c.moneda);e.className='pos-diferencia '+(Math.abs(d)<.01?'ok':'error');}
function cajaEstadoHtml(){var c=cajaActualAbierta();if(!c)return '<div class="pos-panel" style="margin-bottom:14px"><div class="pos-section-title">Caja cerrada</div><button class="btn btn-p" onclick="cajaAbrirModal()">Abrir caja</button></div>';var r=cajaResumen(c),u=c.usuarioApertura&&c.usuarioApertura.nombre||'Usuario';return '<div class="pos-panel" style="margin-bottom:14px"><div class="pos-section-title"><span>Estado: ABIERTA</span><span>'+posFecha(c.aperturaFechaHora)+'</span></div><div class="sc-row"><div class="sc"><div class="scl">Usuario</div><div class="scv" style="font-size:14px">'+esc(u)+'</div></div><div class="sc"><div class="scl">Efectivo inicial</div><div class="scv cb">'+posDinero(c.efectivoInicial,c.moneda)+'</div></div><div class="sc"><div class="scl">Efectivo esperado</div><div class="scv cg">'+posDinero(r.efectivoEsperado,c.moneda)+'</div></div></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px"><button class="btn btn-g btn-sm" onclick="cajaMovimientoModal(1)">+ Ingreso manual</button><button class="btn btn-g btn-sm" onclick="cajaMovimientoModal(-1)">- Egreso manual</button><button class="btn btn-d btn-sm" onclick="cajaCerrarModal()">Cerrar caja</button></div></div>';}
function cajaMapaHtml(t,m){var ks=Object.keys(m||{});return '<div class="pos-section-title pos-mov-title">'+esc(t)+'</div><div class="pos-lista">'+(ks.map(function(k){var mo=k.slice(-3);return '<div class="pos-list-row"><span>'+esc(k)+'</span><b>'+posDinero(m[k],mo)+'</b></div>';}).join('')||'<div class="pos-vacio">Sin movimientos</div>')+'</div>';}
function renderCierresCaja(){
  if(!puede('ver_cierres_caja')){showView('reps');return;}
  var cnt=el('cnt'),lista=(window.CIERRES_CAJA||[]).filter(function(c){return c.estado==='cerrada';});
  if(window.CIERRES_CAJA_CARGANDO){cnt.innerHTML='<div class="empty"><div class="ei">⏳</div>Cargando cierres de caja...</div>';return;}
  if(window.CIERRES_CAJA_ERROR){cnt.innerHTML='<div class="empty"><div class="ei">⚠️</div>No se pudieron cargar los cierres de caja.<small style="display:block;margin-top:8px">'+esc(window.CIERRES_CAJA_ERROR)+'</small></div>';return;}
  cnt.innerHTML='<div class="toolbar"><select id="cfTipo" class="fsel" onchange="cajaFiltrarCierres()"><option value="mes">Mes</option><option value="dia">Día</option><option value="anio">Año</option><option value="rango">Rango personalizado</option></select><input id="cfDesde" type="date" aria-label="Desde" onchange="cajaFiltrarCierres()"><input id="cfHasta" type="date" aria-label="Hasta" onchange="cajaFiltrarCierres()"></div><div id="cierresLista"></div>';
  window._CIERRES_FILTRABLES=lista;
  var h=new Date(),desde=el('cfDesde'),hasta=el('cfHasta');
  desde.value=h.getFullYear()+'-'+String(h.getMonth()+1).padStart(2,'0')+'-01';hasta.value=h.getFullYear()+'-'+String(h.getMonth()+1).padStart(2,'0')+'-'+String(h.getDate()).padStart(2,'0');
  cajaFiltrarCierres();
}
function cajaHora(v){if(!v)return '—';var d=new Date(v);return isNaN(d)?String(v):d.toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'});}
function cajaFiltrarCierres(){
  var tipo=val('cfTipo'),d=val('cfDesde'),h=val('cfHasta'),lista=(window._CIERRES_FILTRABLES||[]).filter(function(c){var f=c.fechaNegocio||'';if(tipo==='dia')return f===d;if(tipo==='anio')return f.slice(0,4)===d.slice(0,4);if(tipo==='mes')return f.slice(0,7)===d.slice(0,7);return (!d||f>=d)&&(!h||f<=h);});
  el('cierresLista').innerHTML='<div class="pos-lista">'+(lista.map(function(c){var usuario=c.usuarioCierre&&c.usuarioCierre.nombre||c.usuarioApertura&&c.usuarioApertura.nombre||'—';return '<button class="pos-list-row" onclick="cajaVerCierre(\''+c.id+'\')"><span><b>'+esc(c.fechaNegocio||'—')+' · '+esc(usuario)+'</b><small>Apertura '+cajaHora(c.aperturaFechaHora)+' · Cierre '+cajaHora(c.cierreFechaHora)+'</small></span><span><b>Contado '+posDinero(c.efectivoContado,c.moneda)+'</b><small>Inicial '+posDinero(c.efectivoInicial,c.moneda)+' · Esperado '+posDinero(c.efectivoEsperado,c.moneda)+' · Total cobrado '+posDinero(c.totalIngresos,c.moneda)+'</small></span><b class="'+(Math.abs(Number(c.diferencia||0))>.01?'pos-out':'pos-in')+'">Dif. '+posDinero(c.diferencia,c.moneda)+'</b></button>';}).join('')||'<div class="pos-vacio">Sin cierres para el período.</div>')+'</div>';
}
function cajaMovimientosCierreHtml(movs){return '<div class="pos-section-title pos-mov-title">Ingresos y egresos</div><div class="pos-lista">'+((movs||[]).map(function(m){var n=Number(m.monto||0);return '<div class="pos-list-row"><span><b>'+esc(m.descripcion||m.categoria||m.tipo||'Movimiento')+'</b><small>'+posFecha(m.fechaHora)+' · '+esc(m.medio||'Sin medio')+' · '+esc(m.cuenta||'Sin cuenta')+' · '+esc(m.usuario&&m.usuario.nombre||'')+'</small></span><b class="'+(n<0?'pos-out':'pos-in')+'">'+(n>0?'+':'')+posDinero(n,m.moneda)+'</b></div>';}).join('')||'<div class="pos-vacio">Sin movimientos asociados.</div>')+'</div>';}
function cajaDetalleHtml(c,movs){
  var obs=[c.observacionApertura,c.observacionCierre].filter(Boolean).join(' · ')||'Sin observaciones';
  return '<div class="pos-ticket-preview"><div><span>Fecha</span><b>'+esc(c.fechaNegocio||'—')+'</b></div><div><span>Hora de apertura / cierre</span><b>'+cajaHora(c.aperturaFechaHora)+' / '+cajaHora(c.cierreFechaHora)+'</b></div><div><span>Efectivo inicial</span><b>'+posDinero(c.efectivoInicial,c.moneda)+'</b></div><div><span>Ingresos</span><b>'+posDinero(c.totalIngresos,c.moneda)+'</b></div><div><span>Egresos</span><b>'+posDinero(c.totalEgresos,c.moneda)+'</b></div><div><span>Esperado</span><b>'+posDinero(c.efectivoEsperado,c.moneda)+'</b></div><div><span>Contado</span><b>'+posDinero(c.efectivoContado,c.moneda)+'</b></div><div class="total"><span>Diferencia</span><b>'+posDinero(c.diferencia,c.moneda)+'</b></div><small>Abrió: '+esc(c.usuarioApertura&&c.usuarioApertura.nombre||'—')+' · Cerró: '+esc(c.usuarioCierre&&c.usuarioCierre.nombre||'—')+'</small><small>Observaciones: '+esc(obs)+'</small></div>'+cajaMovimientosCierreHtml(movs)+cajaMapaHtml('Totales por medio',c.totalesPorMedio)+cajaMapaHtml('Totales por cuenta',c.totalesPorCuenta);
}
function cajaVerCierre(id){var c=(window.CIERRES_CAJA||[]).find(function(x){return x.id===id;});if(!c)return;posModal('Cierre '+(c.fechaNegocio||''),cajaDetalleHtml(c,[]),posCerrarModal,'Cerrar');if(!window.FB||typeof FB.cargarMovimientosCaja!=='function')return;FB.cargarMovimientosCaja(id,function(err,movs){if(err){toast('No se pudo cargar el detalle: '+err,'var(--rd)');return;}var body=document.querySelector('#posModal .mb');if(body)body.innerHTML=cajaDetalleHtml(c,movs);});}
